### ISSUE TITLE
Node migration doesn't migrate all the nodes

### ISSUE THREAD

**Issue by amool** [amool/migrate_drupal7#1]
The `innerJoin` that is used in [Plugin/migrate/source/Node.php](https://github.com/amool/migrate_drupal7/blob/4242929ef90929b3acfdd09107e2f1819a67efc0/src/Plugin/migrate/source/Node.php#L53) doesn't let migration of all the nodes. It only migrates the nodes which are in both `node` table and `field_data_body`. Which are only nodes of type `page`

**Comment by amool** [comment]
used `leftJoin` instead of `innerJoin` in [Plugin/migrate/source/Node.php](https://github.com/amool/migrate_drupal7/blob/4242929ef90929b3acfdd09107e2f1819a67efc0/src/Plugin/migrate/source/Node.php#L53) hoping to solve the problem. Still it doesn't migrate all the nodes. Just migrates only `page` nodes. I wonder why?

**Comment by amool** [comment]
instead joining the `node` & `field_data_body` tables just wanted to migrate `node` table and ditch the `Body` field data. Surprisingly, none of the nodes are migrated and there are no errors (`migrate_message_d7_node` table is empty). 

Upon checking the migrate_map table from d7_node migration `migrate_map_d7_node` table (as you can see in the following picture) has sourceid1 but the destid1 is empty:
![image](https://cloud.githubusercontent.com/assets/6901282/3396488/92f9c0fc-fd0f-11e3-91e5-40a47b51fdfb.png)

I've no clue why this is happening.

**Comment by amool** [comment]
Sprinkling `print` statements here and there in the `migrate` module, finally I think I found the error:
in `core\modules\migrate\src\MigrateExecutable.php`. `MigrateSkipRowException` is caught. Upon printing that exception. the following is printed for each row in `node` table.

```
exception 'Drupal\migrate\MigrateSkipRowException' in H:\xampp\htdocs\d8.x-dev_test\core\modules\migrate\src\Plugin\migrate\process\StaticMap.php:50
Stack trace:
#0 H:\xampp\htdocs\d8.x-dev_test\core\modules\migrate\src\MigrateExecutable.php(394): Drupal\migrate\Plugin\migrate\process\StaticMap->transform(NULL, Object(Drupal\migrate\MigrateExecutable), Object(Drupal\migrate\Row), 'body.format')
#1 H:\xampp\htdocs\d8.x-dev_test\core\modules\migrate\src\MigrateExecutable.php(266): Drupal\migrate\MigrateExecutable->processRow(Object(Drupal\migrate\Row))
#2 C:\Users\Amool\AppData\Roaming\Composer\vendor\drush\drush\commands\core\migrate.d8.drush.inc(51): Drupal\migrate\MigrateExecutable->import()
#3 [internal function]: drush_migrate_manifest('manifest.yml')
#4 C:\Users\Amool\AppData\Roaming\Composer\vendor\drush\drush\includes\command.inc(363): call_user_func_array('drush_migrate_m...', Array)
#5 C:\Users\Amool\AppData\Roaming\Composer\vendor\drush\drush\includes\command.inc(214): _drush_invoke_hooks(Array, Array)
#6 [internal function]: drush_command('manifest.yml')
#7 C:\Users\Amool\AppData\Roaming\Composer\vendor\drush\drush\includes\command.inc(182): call_user_func_array('drush_command', Array)
#8 C:\Users\Amool\AppData\Roaming\Composer\vendor\drush\drush\drush.php(105): drush_dispatch(Array)
#9 C:\Users\Amool\AppData\Roaming\Composer\vendor\drush\drush\drush.php(68): _drush_bootstrap_and_dispatch()
#10 C:\Users\Amool\AppData\Roaming\Composer\vendor\drush\drush\drush.php(16): drush_main()
#11 {main}
```

The line 394 (in processRow method):

```
      try {
        $value = $plugin->transform($value, $this, $row, $destination);
      }
```

comparing that with that the error in exception, $destination is 'body.format'. And it is trying to transform null value to one of the body.format, I guess.

Now that is the problem, as no where in the my module I'm using `body.format` as desitnation field. I deleted everything related to body from my code, re-installed the module, deleted migrate_message_d7_node &  migrate_map_d7_node tables from the database, rebuilt the cache, then ran this migration.

I've no clue why `body.format` is coming into picture.

**Comment by amool** [comment]
I don't know what exactly the problem is but 
I suspect that because nodes of type lesson & ladder don't have body field. treating all nodes alike might be causing the problem. So separating the migrations for each content-type. Hoping that would work.

**Comment by amool** [comment]
In my last 3 commits I've seperated node migration into 3 different migrations. One for each content-type: page, lesson, ladder. So for migration of nodes all three migrations has be executed.

https://github.com/amool/migrate_drupal7/tree/c7e26996d7f16edc8143023c3992ed658b27663b
